<a href="https://colab.research.google.com/github/BetoxAlka/AnaliticaDatos/blob/main/Actividad3_4_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importamos las librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
#Cargar un archivo
from google.colab import files
files.upload()

In [ ]:
#Crear DataFrame
data = pd.read_csv('Base_Socio_Formador_Con_Nulos.csv',encoding='latin-1')
data.head(5)

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = data.isnull().sum()
valores_nulos

fecha               12
precio              31
año_hecho           10
año_renovado        20
metros_cuadrados    26
pisos               19
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Se realiza una copia del DataFrame
df = data.copy()

In [ ]:
#Sustituir valores nulos con string definido
df['fecha'] = df['fecha'].fillna('31/12/3000') #Se establece una fecha sumamente lejana para poner una limite extremo
df #Dicho limite ayudara a que durante el anaisis de dato se conozcan aquellos datos cuyas fechas son exageradas (No fueron registradas correctamente)

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,NaN,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio              31
año_hecho           10
año_renovado        20
metros_cuadrados    26
pisos               19
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion1.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion1.csv')

In [ ]:
#Sustituir valores nulos con string concreto
df['precio'] = df['precio'].fillna('$0') #Dado que no puden exisitir precios de 0, se establece este valor limite extremo
df #De esta manera se define el limite donde se encuentran aquellos registros donde el precio no fue almacenado correctamente

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho           10
año_renovado        20
metros_cuadrados    26
pisos               19
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion2.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion2.csv')

In [ ]:
#Sustituir valores nulos con string definido
df['año_hecho'] = df['año_hecho'].fillna('31/12/3000') #Se establece una fecha sumamente lejana para poner una limite extremo
df #Dicho limite ayudara a que durante el anaisis de dato se conozcan aquellos datos cuyas fechas son exageradas (No fueron registradas correctamente)

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado        20
metros_cuadrados    26
pisos               19
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion3.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion3.csv')

In [ ]:
#Sustituir valores nulos con un valor concreto
df['año_renovado'] = df['año_renovado'].fillna(3000.0) #Se sustituyen los valores con un valor exagerado y lejano
df #De esta manera se puede mantener el conocimiento acerca de aquellos registros cuyos datos no fueron almacenados correctamente

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados    26
pisos               19
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion4.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion4.csv')

In [ ]:
#Sustituir valores nulos con la media de la columna
df['metros_cuadrados'] = df['metros_cuadrados'].fillna(round(data['metros_cuadrados'].mean(),))
df #Se sustituyen los valores nulos por el promedio de la columna (del Frame original para evitar errores de actualizacion de datos)
#Se eligio este metodo pues resulta util al establecer un valor concordante con el resto de ventas

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos               19
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion5.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion5.csv')

In [ ]:
#Sustituir valores nulos con la mediana de la columna
df['pisos'] = df['pisos'].fillna(round(data['pisos'].median(),2))
df #Se sustituyen los valores nulos por la mediana de la columna (del Frame original para evitar errores por la actualizacion de datos)
#Se eligio este metodo pues resulta util al establecer un valor estandar con el resto de ventas

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos                0
habitaciones        11
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion6.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion6.csv')

In [ ]:
#Sustituir valores nulos con la mediana de la columna
df['habitaciones'] = df['habitaciones'].fillna(round(data['habitaciones'].median(),2))
df #Se sustituyen los valores nulos por la mediana de la columna (del Frame original para evitar errores por la actualizacion de datos)
#Se eligio este metodo pues resulta util al establecer un valor estandar con el resto de ventas

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos                0
habitaciones         0
baños               13
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion7.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion7.csv')

In [ ]:
#Sustituir valores nulos con la mediana de la columna
df['baños'] = df['baños'].fillna(round(data['baños'].median(),2))
df #Se sustituyen los valores nulos por la mediana de la columna (del Frame original para evitar errores por la actualizacion de datos)
#Se eligio este metodo pues resulta util al establecer un valor estandar con el resto de ventas

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos                0
habitaciones         0
baños                0
calle               26
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion8.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion8.csv')

In [ ]:
#Sustituir valores nulos con un string concreto
df['calle'] = df['calle'].fillna('0000 NON ST') #Se establece un string concreto e inexistente
df #Para asi establecer aquellos registros donde los datos no fueron correctamente almacenados

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos                0
habitaciones         0
baños                0
calle                0
codigo_zip          20
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion9.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion9.csv')

In [ ]:
#Sustituir valores nulos con un valor concreto
df['codigo_zip'] = df['codigo_zip'].fillna(99999.0) #Se establece un valor sumamente exagerado que defina el limite extremo
df #Mediante este valor podemos definir durante el analizis aquellos registros donde los datos no fueron correctamente registrados

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos                0
habitaciones         0
baños                0
calle                0
codigo_zip           0
estado               6
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion10.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion10.csv')

In [ ]:
#Sustituir valores nulos con un string concreto
df['estado'] = df['estado'].fillna('00') #Se establece un string concreto e inexistente
df #Para asi establecer aquellos registros donde los datos no fueron correctamente almacenados

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha                0
precio               0
año_hecho            0
año_renovado         0
metros_cuadrados     0
pisos                0
habitaciones         0
baños                0
calle                0
codigo_zip           0
estado               0
ciudad              19
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion11.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion11.csv')

In [ ]:
#Sustituir valores nulos con un string concreto
df['ciudad'] = df['ciudad'].fillna('NADA') #Se establece un string concreto e inexistente
df #Para asi establecer aquellos registros donde los datos no fueron correctamente almacenados

,fecha,precio,año_hecho,año_renovado,metros_cuadrados,pisos,habitaciones,baños,calle,codigo_zip,estado,ciudad
0,24/06/2019,"$260,070",01/01/1982,2016.0,762.0,1.0,4.0,2.0,2400 WALNUT RIDGE ST,75229.0,TX,DALLAS
1,18/07/2019,"$456,280",01/01/1982,2016.0,866.0,2.0,4.0,2.0,10400 BIG THICKET DR,75217.0,TX,DALLAS
2,31/07/2019,"$237,820",01/01/1982,2016.0,814.0,1.0,5.0,3.0,9200 DARTWOOD LN,75225.0,TX,DALLAS
3,14/08/2019,"$231,000",01/01/1980,2016.0,680.0,1.0,4.0,2.0,4800 SIMCOE ST,75228.0,TX,DALLAS
4,31/07/2019,"$1,410,820",01/01/1980,2016.0,1018.0,2.0,4.0,2.0,6926 STEFANI DR,75225.0,TX,DALLAS
...,...,...,...,...,...,...,...,...,...,...,...,...
4354,04/07/2019,$0,01/01/1928,0.0,305.0,1.0,2.0,1.0,1301 HAMEL ST,75212.0,TX,DALLAS
4355,14/06/2019,"$257,360",01/01/1928,0.0,299.0,1.0,2.0,1.0,3501 WORD ST,75204.0,TX,DALLAS
4356,16/07/2019,"$881,200",01/01/1927,0.0,817.0,2.0,5.0,3.0,1700 RIDGEDORF DR,75217.0,TX,DALLAS
4357,05/08/2019,"$877,080",01/01/1927,0.0,576.0,2.0,4.0,2.0,8024 ROTHINGTON RD,75227.0,TX,DALLAS
4358,14/08/2019,"$660,180",01/01/1927,0.0,393.0,1.0,3.0,1.0,8201 BARBAREE BLVD,75228.0,TX,DALLAS

In [ ]:
#Conocer las columnas con valores nulos
valores_nulos = df.isnull().sum()
valores_nulos

fecha               0
precio              0
año_hecho           0
año_renovado        0
metros_cuadrados    0
pisos               0
habitaciones        0
baños               0
calle               0
codigo_zip          0
estado              0
ciudad              0
dtype: int64

In [ ]:
#Convertir DataFrame a csv
df.to_csv('Sustitucion12.csv')

#Descargar archivo
from google.colab import files
files.download('Sustitucion12.csv')